version: '3.5'

services:
  postgres:
    container_name: multitenancy_postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mega_secure_password
      - POSTGRES_USER=demo_data_center
      - POSTGRES_DB=demo_data_center
    networks:
      - multitenancy_network
    ports:
      - "127.0.0.1:5432:5432"
  service:
    container_name: multitenancy_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - multitenancy_network
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/survey_pricing
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/survey_pricing
    depends_on:
      - postgres

networks:
  multitenancy_network:
    driver: bridge
