spring:
  profiles:
    active: dev
    group:
      dev:
        - dev
        - api-docs
  liquibase:
    enabled: false
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/demo_lab
    username: demo_lab
    password: mega_secure_password
    hikari:
      minimum-idle: 90
      maximum-pool-size: 90
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.jdbc.core: INFO

datasource:
  base-url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/}
  main:
    name: ${MAIN_DB_NAME:demo_lab}
    driver: ${MAIN_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${MAIN_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo_lab}
    username: ${MAIN_DATASOURCE_USERNAME:demo_lab}
    password: ${MAIN_DATASOURCE_PASSWORD:mega_secure_password}

driver: org.postgresql.Driver
url: ${spring.datasource.url}
username: ${spring.datasource.username}
password: ${spring.datasource.password}