spring:
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  liquibase:
    enabled: false
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/demo_data_center
    username: demo_data_center
    password: mega_secure_password
    hikari:
      minimum-idle: 90
      maximum-pool-size: 90
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  task:
    scheduling:
      pool:
        size: 1

  mail:
    host: ${SMTP_SERVER:email-smtp.eu-central-1.amazonaws.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_AUTH_USER:AKIAVQL5AQAFMLUOA3HL}
    password: ${SMTP_AUTH_PASS:BPlJym3jpeJqxUc6vy9958lxL+ZVCE9RYXDaHRv5NX2e}
    sender: ${SENDER_ADDRESS:noreply@businessapps-stg.simon-kucher.com}
    protocol: smtp
    properties.mail.smtp:
      starttls.enable: true
      starttls.required: true
      ssl.enable: true
      properties.mail.smtps:
        auth: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /docs

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.jdbc.core: INFO

twilio:
  sms:
    sid: sid
    token: token
    phone: +4915735982170

bmsapi:
  host:
    url: https://host
  username: Impltech
  password: pass

datasource:
  base-url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/}
  main:
    name: ${MAIN_DB_NAME:demo_data_center}
    driver: ${MAIN_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${MAIN_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo_data_center}
    username: ${MAIN_DATASOURCE_USERNAME:demo_data_center}
    password: ${MAIN_DATASOURCE_PASSWORD:mega_secure_password}
  test:
    impltech:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/pic_tenant
      username: pic_tenant
      password: pass_for_test_db

project:
  secret: ${CLIENT_SECRET:mNp59VI3s9bSgLGT0M5j2Dy9iHPZHclb}
  client-id: ${CLIENT_ID:pic}
  sync-token: ${SYNC_TOKEN:N6308zAE0XudTT4bGGZCcciWA8z0Wjsu}
  redirect-uri: ${REDIRECT_URI:https://dev-survey-pricing.impltech.com/oauth2/callback}

scheduled:
  amount:
    first_survey_answers_customers: 2000
    first_survey_answers_bu: 5000
    second_survey_answers: 2000
    negotiations: 75

api:
  business-apps: https://businessapps-stg.simon-kucher.com

jwt:
  secret: 4qnaaFbEuHkrhNHCZX59RuIF4fWhjYPbpkBrfsfsdfsGfE0iQ87WfSVfxer8tzfE70wXqlgdufJJ42QTQs123dhtkndS347CU

code:
  expiration:
    time: 60000

threads:
  amount:
    excel: 1000

token:
  accountManager:
    expiration:
      time:
        ms: 7776000000
  admin:
    expiration:
      time:
        ms: 86400000
    remember:
      expiration:
        time:
          ms: 2592000000

driver: org.postgresql.Driver
url: ${spring.datasource.url}
verbose: true
dropFirst: false
username: ${spring.datasource.username}
password: ${spring.datasource.password}

environment: ${ENVIRONMENT:PROD}

test.cron: '* */5 * * * *'
